### ISSUE TITLE
Little doc about api

### ISSUE THREAD

**Issue by labs20** [Astro36/word2vec4node#4]
Hi. 

I know there are plenty documentation around (mostly in pyhton) about word2vec and doc2vec, but it could be very useful to get some info about the functions of this lib.

I've navigated through the sources and made some guess, but a more clear explanation about the "how, when, (and mostly) why" to use the functions and its parameters would be very appreciated especially for those (like me) that are at the start and trying to figure this whole NLP thing out.

Could you please add some info about it?

Thanks again!

**Comment by Astro36** [comment]
This project started three years ago as a toy project.
Unfortunately, I don't have time for additional management other than minimal maintenance at the moment due to other project developments.

Thank you for your interest and sorry for not being able to help.
If there is something to be fixed, please contribute to the project with Pull Request.

**Comment by labs20** [comment]
Hi! I'd like to say thanks you for your work and for being so kind to share it. 

Thank you!

I understand. If you ever find the time to at least put some comments at the functions, that already would be of great help, but as I said, I understand =]

Thanks!
